//wap to create student information management application
#include<stdio.h>
int main()
{char n1[10],n2[10],n3[10],n4[10],n5[10],n6[10],n7[10],n8[10],n9[10],n10[10],c1[10],c2[10],c3[10],c4[10],
c5[10],c6[10],c7[10],c8[10],c9[10],c10[10],f1[10],f2[10],f3[10],f4[10],f5[10],f6[10],f7[10],f8[10],f9[10],f10[10],
m1[10],m2[10],m3[10],m4[10],m5[10],m6[10],m7[10],m8[10],m9[10],m10[10];
int r1,r2,r3,r4,r5,r6,r7,r8,r9,r10,b1,b2,b3,b4,b5,b6,b7,b8,b9,b10;
printf("\n1)  enter  name of student : \n");
gets(n1);
printf("\nenter college name: \n");
gets(c1);
printf("\nenter branch name : \n");
gets(f1);
printf("\nenter mobile no : \n");
gets(m1);
printf("\nenter roll no,batch time  : \n");
scanf("%d%d",&r1,&b1);
printf("\n2)  enter  name of student : \n");
gets(n2);
gets(n2);
printf("\nenter college name: \n");
gets(c2);
printf("\nenter branch name : \n");
gets(f2);
printf("\nenter mobile no : \n");
gets(m2);
printf("\nenter roll no,batch time  : \n");
scanf("%d%d",&r2,&b2);
printf("\n3)  enter  name of student : \n");
gets(n3);
gets(n3);
printf("\nenter college name: \n");
gets(c3);
printf("\nenter branch name : \n");
gets(f3);
printf("\nenter mobile no : \n");
gets(m3);
printf("\nenter roll no,batch time  : \n");
scanf("%d%d",&r3,&b3);
printf("\n4)  enter  name of student : \n");
gets(n4);
gets(n4);
printf("\nenter college name: \n");
gets(c4);
printf("\nenter branch name : \n");
gets(f4);
printf("\nenter mobile no : \n");
gets(m4);
printf("\nenter roll no,batch time  : \n");
scanf("%d%d",&r4,&b4);
printf("\n5)  enter  name of student : \n");
gets(n5);
gets(n5);
printf("\nenter college name: \n");
gets(c5);
printf("\nenter branch name : \n");
gets(f5);
printf("\nenter mobile no : \n");
gets(m5);
printf("\nenter roll no,batch time  : \n");
scanf("%d%d",&r5,&b5);
printf("\n6)  enter  name of student : \n");
gets(n6);
gets(n6);
printf("\nenter college name: \n");
gets(c6);
printf("\nenter branch name : \n");
gets(f6);
printf("\nenter mobile no : \n");
gets(m6);
printf("\nenter roll no,batch time  : \n");
scanf("%d%d",&r6,&b6);
printf("\n7)  enter  name of student : \n");
gets(n7);
gets(n7);
printf("\nenter college name: \n");
gets(c7);
printf("\nenter branch name : \n");
gets(f7);
printf("\nenter mobile no : \n");
gets(m7);
printf("\nenter roll no,batch time  : \n");
scanf("%d%d",&r7,&b7);
printf("\n8)  enter  name of student : \n");
gets(n8);
gets(n8);
printf("\nenter college name: \n");
gets(c8);
printf("\nenter branch name : \n");
gets(f8);
printf("\nenter mobile no : \n");
gets(m8);
printf("\nenter roll no,batch time  : \n");
scanf("%d%d",&r8,&b8);
printf("\n9)  enter  name of student : \n");
gets(n9);
gets(n9);
printf("\nenter college name: \n");
gets(c9);
printf("\nenter branch name : \n");
gets(f9);
printf("\nenter mobile no : \n");
gets(m9);
printf("\nenter roll no, batch time  : \n");
scanf("%d%d",&r9,&b9);
printf("\n10)  enter  name of student : \n");
gets(n10);
gets(n10);
printf("\nenter college name: \n");
gets(c10);
printf("\nenter branch name : \n");
gets(f10);
printf("\nenter mobile no : \n");
gets(m10);
printf("\nenter roll no,batch time  : \n");
scanf("%d%d",&r10,&b10);

printf("\n------------------------------------------------------------------------------------------------------------------------");
printf("\nRoll number\t|  Name\t\t|  Mobile no.\t|  college name\t|  batch time\tbranch  |");
printf("\n------------------------------------------------------------------------------------------------------------------------");
printf("\n%d\t\t|  %s\t|  %s\t|  %s\t| %d\t\t|  %s  | ",r1,n1,m1,c1,b1,f1);
printf("\n------------------------------------------------------------------------------------------------------------------------");
printf("\n%d\t\t|  %s\t|  %s\t|  %s\t| %d\t\t|  %s  | ",r2,n2,m2,c2,b2,f2);
printf("\n------------------------------------------------------------------------------------------------------------------------");
printf("\n%d\t\t|  %s\t|  %s\t|  %s\t| %d\t\t|  %s  | ",r3,n3,m3,c3,b3,f3);
printf("\n------------------------------------------------------------------------------------------------------------------------");
printf("\n%d\t\t|  %s\t|  %s\t|  %s\t| %d\t\t|  %s  | ",r4,n4,m4,c4,b4,f4);
printf("\n------------------------------------------------------------------------------------------------------------------------");
printf("\n%d\t\t|  %s\t|  %s\t|  %s\t| %d\t\t|  %s  | ",r5,n5,m5,c5,b5,f5);
printf("\n------------------------------------------------------------------------------------------------------------------------");
printf("\n%d\t\t|  %s\t|  %s\t|  %s\t| %d\t\t|  %s  | ",r6,n6,m6,c6,b6,f6);
printf("\n------------------------------------------------------------------------------------------------------------------------");
printf("\n%d\t\t|  %s\t|  %s\t|  %s\t| %d\t\t|  %s  | ",r7,n7,m7,c7,b7,f7);
printf("\n------------------------------------------------------------------------------------------------------------------------");
printf("\n%d\t\t|  %s\t|  %s\t|  %s\t| %d\t\t|  %s  | ",r8,n8,m8,c8,b8,f8);
printf("\n------------------------------------------------------------------------------------------------------------------------");
printf("\n%d\t\t|  %s\t|  %s\t|  %s\t| %d\t\t|  %s  | ",r9,n9,m9,c9,b9,f9);
printf("\n------------------------------------------------------------------------------------------------------------------------");
printf("\n%d\t\t|  %s\t|  %s\t|  %s\t| %d\t\t|  %s  | ",r10,n10,m10,c10,b10,f10);
printf("\n------------------------------------------------------------------------------------------------------------------------");
}
